#GET ALL CONTACTS
GET http://localhost:3000/contacts/

GET https://emilio-cse341.onrender.com/contacts/

# GET CONTACT BY ID

GET http://localhost:3000/contacts/6518aa758225c6a1a43cb68a

GET https://emilio-cse341.onrender.com/contacts/6518aa758225c6a1a43cb68a


### CREATE CONTACT

POST http://localhost:3000/contacts/ HTTP/1.1
content-type: application/json

{
    "firstName": "Johnn-local",
    "lastName": "Berckley",
    "email": "johnn-local@byui.edu",
    "birthday": {
    "$date": {
        "$numberLong": "1006560000000"
    }
    },
    "favoriteColor": "purple-black"
}

### Create contact
POST https://emilio-cse341.onrender.com/contacts/ HTTP/1.1
content-type: application/json

{
    "firstName": "Johnn-render",
    "lastName": "Berckley",
    "email": "johnn-render@byui.edu",
    "birthday": {
    "$date": {
        "$numberLong": "1006560000000"
    }
    },
    "favoriteColor": "purple-black"
}


### UPDATE CONTACT
PUT http://localhost:3000/contacts/6518c5546398af68539ea39b HTTP/1.1
content-type: application/json

{
    "email": "natalie-loca@byui.edu"
}

### Update contact

PUT https://emilio-cse341.onrender.com/contacts/6518c5806398af68539ea39e HTTP/1.1
content-type: application/json

{
    "email": "emilio-render@byui.edu"
}

### DELETE CONTACT
DELETE http://localhost:3000/contacts/6518d986321d195282cb9449 HTTP/1.1

### DELETE CONTACT
DELETE https://emilio-cse341.onrender.com/contacts/6518d998ac637cc232f91ed9 HTTP/1.1